dist: stretch

language: php

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: TYPO3_VERSION=^7.6

sudo: false

addons:
  apt:
    packages:
      - parallel
      - jpegoptim
      - optipng
      - pngquant
      - pngcrush
      - gifsicle
      - libjpeg-progs

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - git clone --recursive https://github.com/pornel/pngquant.git
  - cd pngquant && make
  - sudo make install
  - composer self-update
  - composer --version

before_script:
  - phpenv config-rm xdebug.ini
  - composer require typo3/cms=$TYPO3_VERSION
  # Restore composer.json
  - git checkout composer.json
  - export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
  - >
    .Build/bin/phpunit --colors -c .Build/vendor/nimut/testing-framework/res/Configuration/UnitTests.xml Tests/Unit/
