dist: trusty
sudo: false

language: php

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: TYPO3_VERSION=^7.6

addons:
  apt:
    packages:
      - parallel
      - jpegoptim
      - optipng
      - pngquant
      - pngcrush
      - gifsicle
      - libjpeg-progs
      - imagemagick
      - imagemagick-common
      - libmagick++-dev
      - libmagick++4
      - libperl6-slurp-perl
      - libfile-slurp-perl

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - git clone https://github.com/kud/jpegrescan.git
  - ln -s jpegrescan/jpegrescan /usr/local/bin/jpegrescan
  - composer self-update
  - composer --version

before_script:
  - phpenv config-rm xdebug.ini
  - composer require typo3/cms=$TYPO3_VERSION
  # Restore composer.json
  - git checkout composer.json
  - export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
  - >
    .Build/bin/phpunit --colors -c .Build/vendor/nimut/testing-framework/res/Configuration/UnitTests.xml Tests/Unit/
